version: "3.10"

services:
  data-generator-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - QUARKUS_DATASOURCE_DB-KIND=mysql
      - QUARKUS_DATASOURCE_USERNAME=${PROD_MYSQL_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${PROD_MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/${PROD_MYSQL_DB}?enabledTLSProtocols=TLSv1.2
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=update
      - TOTAL_PERSON_TOBE_GENERATED=${TOTAL_PERSON_TOBE_GENERATED}
      - DATA_GENERATOR_MAX_THREAD=10
      - DATA_GENERATOR_RECORDS_PER_THREAD=100
      - DATA_GCP_API_KEY=${GCP_API_KEY}
    ports:
      - "8008:8080"
    volumes:
      - ./:/build/
    networks:
      - mysql-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${PROD_MYSQL_DB}
      - MYSQL_USER=${PROD_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${PROD_MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3360:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysqldb:

networks:
  mysql-network:
    driver: bridge